// AUTO-GENERATED BY THE PIPELINE. Do not edit or delete.
//
// Dynamically imports every page/route module found under this project's
// pages/routes/views/screens directories. `npm run build` would also catch a
// broken import here, but that depends on whoever reads the build log
// recognising a resolution failure as a bug to fix. This test makes the same
// failure a real, unmissable vitest result instead: if an import below cannot
// resolve, THIS test fails, and vitest.xml records it as a failure the pipeline's
// fix loop is required to act on.
//
// If a test below fails: fix the import in the SOURCE file, not this test.
import { describe, it, expect } from 'vitest';


describe('pipeline: route modules resolve', () => {
  it('resolves pages/AdminDashboardPage.tsx', async () => {
    const mod = await import('../pages/AdminDashboardPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/AdminPromotionsPage.tsx', async () => {
    const mod = await import('../pages/AdminPromotionsPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/AdminReviewsPage.tsx', async () => {
    const mod = await import('../pages/AdminReviewsPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/CartPage.tsx', async () => {
    const mod = await import('../pages/CartPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/CategoryListingPage.tsx', async () => {
    const mod = await import('../pages/CategoryListingPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/CheckoutPage.tsx', async () => {
    const mod = await import('../pages/CheckoutPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/HomePage.tsx', async () => {
    const mod = await import('../pages/HomePage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/LoginPage.tsx', async () => {
    const mod = await import('../pages/LoginPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/OrderHistoryPage.tsx', async () => {
    const mod = await import('../pages/OrderHistoryPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/ProductDetailPage.tsx', async () => {
    const mod = await import('../pages/ProductDetailPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/SearchResultsPage.tsx', async () => {
    const mod = await import('../pages/SearchResultsPage');
    expect(mod).toBeDefined();
  });
});
