# AUTO-GENERATED BY THE PIPELINE. Do not edit or delete.
#
# Attempts to import every non-test Python module found in this backend.
# This catches:
#   - packages listed in imports but missing from requirements.txt/pyproject.toml
#   - broken relative imports (e.g. `from .utils import foo` where utils.py is gone)
#   - syntax errors in modules that no existing test exercises
#
# Uses importlib.import_module() — it does NOT call any application code, so
# missing env vars, databases, or external services will not cause false failures.
# If a test below fails: fix the import in the SOURCE module, not this file.
# This file is regenerated on every pass.

import importlib
import pytest

_MODULES = [
    "auth",
    "auth.dependencies",
    "auth.jwt",
    "auth.password",
    "config",
    "database",
    "main",
    "models",
    "models.audit_log",
    "models.cart",
    "models.cart_item",
    "models.category",
    "models.customer",
    "models.discount",
    "models.inventory",
    "models.order",
    "models.order_item",
    "models.product",
    "models.review",
    "models.supplier",
    "models.warehouse",
    "routes",
    "routes.auth",
    "routes.cart",
    "routes.categories",
    "routes.discounts",
    "routes.inventory",
    "routes.orders",
    "routes.products",
    "routes.reviews",
    "routes.search",
    "routes.suppliers",
    "schemas",
    "schemas.auth",
    "schemas.cart",
    "schemas.category",
    "schemas.common",
    "schemas.discount",
    "schemas.inventory",
    "schemas.order",
    "schemas.product",
    "schemas.review",
    "schemas.supplier",
    "seed",
    "services",
    "services.cart_service",
    "services.discount_service",
    "services.inventory_service",
    "services.order_service",
    "services.payment_service",
    "services.product_service",
    "services.review_service",
    "services.supplier_service",
]


@pytest.mark.parametrize('module_name', _MODULES)
def test_module_imports(module_name):
    """Verify the module can be imported without error."""
    mod = importlib.import_module(module_name)
    assert mod is not None
